apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: jenkins
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["create","delete","DeleteCollection","get", "list", "watch"]
